# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0003_add_result_irr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['popularity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='timetrial',
            name='beverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch.Beverage'),
        ),
    ]
