# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0004_add_beverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='timetrial', width_field='width')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('timetrial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopwatch.TimeTrial')),
            ],
        ),
    ]
