# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0007_delete_stopwatch_models'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsProfile',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kasse.Profile')),
                ('ignore', models.BooleanField(blank=True)),
            ],
        ),
    ]
