# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0004_add_beverage'),
        ('news', '0002_newsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timetrials',
            field=models.ManyToManyField(to='stopwatch.TimeTrial'),
        ),
    ]
