# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0007_delete_stopwatch_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['association', 'period', 'title']},
        ),
    ]
