# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0008_title_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('tk', models.CharField(max_length=200)),
                ('alkymia', models.CharField(max_length=200)),
            ],
            options={'ordering': ['event_time']},
        ),
    ]
