# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 10:17
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
import datetime


def add_initial(apps, schema_editor):
    Contest = apps.get_model('kasse', 'Contest')
    data = [
        (2015, 3, 6, '2:43.4', '2:42.6'),
        (2014, 3, 7, '2:10', '6:40'),
        (2013, 3, 8, '2:26', '6:47'),
        (2011, 11, 25, '3:20.9', 'DNF'),
    ]
    for y, m, d, tk, alk in data:
        dt = timezone.localtime(
            datetime.datetime(
                year=y, month=m, day=d, hour=12,
                tzinfo=timezone.utc))
        dt = dt.replace(hour=17)
        Contest(event_time=dt, tk=tk, alkymia=alk).save()


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0009_contest'),
    ]

    operations = [
        migrations.RunPython(add_initial),
    ]
