# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0010_contest_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='alkymia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='tk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
