# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0010_contest_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kasse_i_kass_creator',
            field=models.BooleanField(default=False, verbose_name='Kan oprette "Kasse i KA$$"'),
        ),
    ]
